Controllers/ContactController.cs
using BeautyBook.Common;
using System.Web.Mvc;

namespace Gurupeedam.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ContactUsSend(string SuccessMessage = "",string Con_Subject = "", string con_Fname = "", string col_Lname = "", string email = "", string number = "", string write_message = "")
        {
            EmailHelper.SendEmail(Con_Subject, con_Fname, col_Lname, email, number, write_message);
            EmailHelper.UserSendEmail(email , Con_Subject , SuccessMessage , con_Fname, col_Lname);
            return Json(200, JsonRequestBehavior.AllowGet);
        }

    }
}

Controllers/MindOpeningSessionsController.cs
using System.Web.Mvc;

namespace Gurupeedam.Controllers
{
    public class MindOpeningSessionsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProgramsController.cs
using BeautyBook.Common;
using System.Web.Mvc;

namespace Gurupeedam.Controllers
{
    public class ProgramsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MindOpeningSessions()
        {
            return View();
        }

        public ActionResult Seminars()
        {
            return View();
        }

        public ActionResult SummerWinterCamps()
        {
            return View();
        }

        public ActionResult HeartToHeartCommunication()
        {
            return View();
        }

        public ActionResult AnimalCare()
        {
            return View();
        }


    }
}

Views/Programs/Index.cshtml
@{
    ViewBag.Title = "Programs";
}

<!-- common banner section -->
<section class="desktop-banner">
    <div class="Program-Banner">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="step-banner-content">
                        <h4 data-aos="fade-left" class="cmn-bg-heading colour-white">@(Gurupeedam.Resources.LanguagePrograms.Programs)</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="mobile-banner" style="position:relative;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 p-0">
                <div class="step-banner-content pt-0" style="height:inherit !important;">
                    <img src="~/Content/asset/img/Banners/Programs.jpg" alt="Alternate Text" />
                    <div class="custom-carousel-caption">
                        <h4 data-aos="fade-left" class="cmn-bg-heading colour-white" style="text-align:left;">@(Gurupeedam.Resources.LanguagePrograms.Programs)</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- common banner section -->
<!-- contact form -->
<section>
    <div class="v0nte-contact-form">
        <div class="container">
            <div class="text-center mb-5">
                <h2 class="cmn-title mn-colour"
                    style="text-transform: uppercase; line-height: 1.5; font-size: 17px; ">
                    @(Gurupeedam.Resources.LanguagePrograms.Main_Content)
                </h2>
                <p class="cmn-text">@(Gurupeedam.Resources.LanguagePrograms.Please_Click)</p>
                <p class="cmn-text" style="font-style: italic;">@(Gurupeedam.Resources.LanguagePrograms.Programs_Note)</p>
            </div>
            <div class="row">
                <div class="col-lg-4 p-2">
                    <a href="@Url.Action("MindOpeningSessions","Programs")" class="text-decoration-none">
                        <div class="crd-slide">
                            <div class="img-bx">
                                <img class="slide-img Program-img-cover" src="~/Content/asset/img/animalimages/Mind Realization.png">
                            </div>
                            <div class="btm-section">
                                <h4 class="sldr-title h-truncate-70" title="@(Gurupeedam.Resources.LanguagePrograms.Mind_Realization_Session)">
                                    @(Gurupeedam.Resources.LanguagePrograms.Mind_Realization_Session)
                                </h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 p-2">
                    <a href="@Url.Action("Seminars","Programs")" class="text-decoration-none">
                        <div class="crd-slide">
                            <div class="img-bx">
                                <img class="slide-img Program-img-cover" src="~/Content/asset/img/animalimages/Seminar2.png">
                            </div>
                            <div class="btm-section">
                                <h4 class="sldr-title h-truncate-70" title="@(Gurupeedam.Resources.LanguagePrograms.Seminars)">
                                    @(Gurupeedam.Resources.LanguagePrograms.Seminars)
                                </h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 p-2">
                    <a href="@Url.Action("SummerWinterCamps","Programs")" class="text-decoration-none">
                        <div class="crd-slide">
                            <div class="img-bx">
                                <img class="slide-img Program-img-cover" src="~/Content/asset/img/animalimages/Summer _ Winter Camp.png">
                            </div>
                            <div class="btm-section">
                                <h4 class="sldr-title h-truncate-70" title="@(Gurupeedam.Resources.LanguagePrograms.Summer___Winter_Camps)">
                                    @(Gurupeedam.Resources.LanguagePrograms.Summer___Winter_Camps)
                                </h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 p-2">
                    <a href="@Url.Action("HeartToHeartCommunication","Programs")" class="text-decoration-none">
                        <div class="crd-slide">
                            <div class="img-bx">
                                <img class="slide-img Program-img-cover" src="~/Content/asset/img/animalimages/Heart to Heart.png">
                            </div>
                            <div class="btm-section">
                                <h4 class="sldr-title h-truncate-70" title="@(Gurupeedam.Resources.LanguagePrograms.Heart_to_Heart_Communication)">
                                    @(Gurupeedam.Resources.LanguagePrograms.Heart_to_Heart_Communication)
                                </h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 p-2">
                    <a href="@Url.Action("AnimalCare","Programs")" class="text-decoration-none">
                        <div class="crd-slide">
                            <div class="img-bx">
                                <img class="slide-img Program-img-cover" src="~/Content/asset/img/animalimages/AnimalCare4.jpg">
                            </div>
                            <div class="btm-section">
                                <h4 class="sldr-title h-truncate-70" title="@(Gurupeedam.Resources.LanguagePrograms.Animal_Care)">
                                    @(Gurupeedam.Resources.LanguagePrograms.Animal_Care)
                                </h4>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>

<script>

    //Contact us form jquery validation
    $("#contactForm").validate({
        rules: {
            con_Fname: {
                required: true
            },
            col_Lname: {
                required: true
            },
            email: {
                required: true,
                email:true
            },
            number: {
                required: true,
                number:true
            },
            write_message: {
                required: true
            },
        },
        messages: {
            con_Fname: "First name is required",
            col_Lname: "Last name is required",
            email: {
                required: "Email is required"
            },
            number: {
                required: "Number is required"
            },
            write_message: "Message is required",
        },
        errorPlacement: function (error, element) {
            if (element.is(":radio")) {
                error.appendTo(element.parents('.form-group'));
            }
            else {
                error.insertAfter(element);
            }
        },
        submitHandler: function (form) {
            ContactUs();
        }
    });

    //ContactUs form data ajax call
    function ContactUs() {

        $('#send_button').hide();
        $('#sending_button').show();

        $.ajax({
            type: 'POST',
            url: "@Url.Action("ContactUsSend", "Contact")",
            dataType: 'json',
            data: ({
                Con_Subject: $("#contactForm input[name='con_type']:checked").val(),
                con_Fname: $("#con_Fname").val(),
                col_Lname: $("#col_Lname").val(),
                email: $("#email").val(),
                number: $("#number").val(),
                write_message: $("#write_message").val(),
            }),
            success: function (response) {
                debugger;
                if (response == 200) {
                    alert('Request Submitted Succssfully');
                    window.location.reload();
                } else {
                    alert('Data Not Inserted');
                }
                $('#send_button').show();
                $('#sending_button').hide();
            },
            error: function (response) {
                console.log(response);
                $('#send_button').show();
                $('#sending_button').hide();
            }
        });
    }

</script>